BLACKS_TURN = False
WHITES_TURN = True

BLACK_CHANNEL_INDEX = 0
WHITE_CHANNEL_INDEX = 1
TURN_CHANNEL_INDEX = 2
INVALID_CHANNEL_INDEX = 3
PASS_CHANNEL_INDEX = 4
END_CHANNEL_INDEX = 5

NUM_CHANNELS = 6
